"use client"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { UserContext } from '@lib/context';
import { useUserData } from '@lib/hooks';
import { Toaster } from 'react-hot-toast';

export default function RootLayout({ children }) {
  const userData = useUserData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext.Provider value={userData}>
          {children}
          <Toaster />
        </UserContext.Provider>
      </body>
    </html >
  );
}
